version: "3.3"

services:
  api:
    image: node:18.0.0
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/jobmatch
    links:
      - mongo
    depends_on:
      - nats
      - mongo
    ports:
      - 9000:3000
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: sh -c "npm i && npm run dev"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-gw.rule=PathPrefix(`/api`) && Host(`localhost`)"
      - "traefik.http.services.api-gw.loadbalancer.server.port=3000"
    networks:
      - internal

  mongo:
    image: mongo:4
    ports:
      - 27017
    volumes:
      - data:/data/db
    networks:
      - internal

  nats:
    image: nats:2
    networks:
      - internal

  traefik:
    image: traefik:v2.4
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --api.insecure=true # Enable insecure API access
      - --log.level=DEBUG
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal
      - default

networks:
  internal:

volumes:
  data:
